### ISSUE TITLE
User experience at the prompt

### ISSUE THREAD

**Issue by jerryjohnjacob** [kishore-narendran/AliensOnEarth#7]
Consider this was a live system being used by real people. The menu that would be displayed to them would prompt asking using names such as _noOfAntennas_. The menu should present more human-friendly terms such as _Number of Antennas_.

**Comment by kishore-narendran** [comment]
Fixed in 8b41c4f9e555f105ab637bfae84fddf017881029, however this changes the JSON object returned too from the prompt input. The [prompt](https://github.com/flatiron/prompt) library, does not currently allow for aliasing of parameters, hence JSON key naming conventions are not currently being followed. The changes in parameters have been changed in the README.md  in 3b340b163527f75245db6ca7112ab6cf87726d96
